### PR TITLE
Allow clients to grab a copy of the history.

### PR DESCRIPTION
**Pull request by egranata**
This is useful for two reasons:
 - it allows clients of the library to not maintain two copies
   of the history as they add elements to it;
 - it allows clients access to history elements from a previous
   run being loaded from disk without having to duplicate
   the logic to parse those items into a buffer they maintain.

### CODE REVIEW

**Comment by rain-1** [comment]
Thank you. I like the idea here

I don't think it is clear enough that `char** dest` in  `linenoiseHistoryCopy` must have been pre-allocated to hold the items. I will add a comment explaining that.

**Comment by rain-1** [comment]
https://github.com/rain-1/linenoise-mob/commit/a2d0d52451ed8b118ef4bb50fd7252f80e11f0b4 here is the 
change. Also removed the NULL check since it will not be NULL if the buffer has been allocated already.

**Comment by egranata** [comment]
> [a2d0d52](https://github.com/rain-1/linenoise-mob/commit/a2d0d52451ed8b118ef4bb50fd7252f80e11f0b4) here is the
> change. Also removed the NULL check since it will not be NULL if the buffer has been allocated already.

Yeah good point. Thanks for merging so quickly :)

**Comment by rain-1** [comment]
Thank you for the contribution!

**Pull request merged**
