### PR TITLE
Haiku port

### PR DESCRIPTION
**Pull request by mmuman**
These make it work on Haiku.

### CODE REVIEW

**Comment by mmuman** [comment]
Hmm I'm concerned about the utf8.h header in includes/ … shouldn't it be in a subdir?

I wrote a [haikuports](https://github.com/haikuports/haikuports/) recipe. The base package is empty because no dynamic lib, not sure I should make one though…

**Comment by rain-1** [comment]
Can you tell me what you mean about utf8.h? Would you prefer it to be put into something like includes/linenoise/utf8.h

**Comment by mmuman** [comment]
Yeah, it would make more sense I think. The name is generic enough it could collide with a system header. On Haiku at least we have a UTF8.h header in os/support (but it's in the default search path) for example.
Now, do you really need a separate header for just 3 functions?

**Comment by mmuman** [comment]
There you go, [recipe available](https://github.com/haikuports/haikuports/commit/b502a38e6d42c13c08f33e781421eb64ca2e4dc5) ;-)

**Pull request merged**
